[package]
name = "util_http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isahc.workspace = true
anyhow.workspace = true
futures.workspace = true
serde_json.workspace = true
smol.workspace = true
serde.workspace = true
log.workspace = true
url = "2.2"

[features]
test-support = []

[dev-dependencies]
tempdir.workspace = true
