[package]
name = "settings2"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/settings2.rs"
doctest = false

[features]
test-support = ["gpui/test-support", "fs/test-support"]

[dependencies]
collections = { path = "../collections" }
gpui = {package = "gpui2",  path = "../gpui2" }
sqlez = { path = "../sqlez" }
fs = {package = "fs2",  path = "../fs2" }
feature_flags = {package = "feature_flags2",  path = "../feature_flags2" }
util = { path = "../util" }

anyhow.workspace = true
futures.workspace = true
serde_json_lenient = {version = "0.1", features = ["preserve_order", "raw_value"]}
lazy_static.workspace = true
postage.workspace = true
rust-embed.workspace = true
schemars.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
smallvec.workspace = true
toml.workspace = true
tree-sitter.workspace = true
tree-sitter-json = "*"

[dev-dependencies]
gpui = {package = "gpui2",  path = "../gpui2", features = ["test-support"] }
fs = { package = "fs2", path = "../fs2", features = ["test-support"] }
indoc.workspace = true
pretty_assertions.workspace = true
unindent.workspace = true
