[package]
name = "anthropic_ai"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/anthropic_ai.rs"

[dependencies]
anyhow.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
util.workspace = true
