[package]
name = "install_cli2"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/install_cli2.rs"

[features]
test-support = []

[dependencies]
smol.workspace = true
anyhow.workspace = true
log.workspace = true
serde.workspace = true
gpui = { package = "gpui2", path = "../gpui2" }
util = { path = "../util" }
