[package]
name = "context_menu2"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/context_menu.rs"
doctest = false

[dependencies]
gpui = { package = "gpui2", path = "../gpui2" }
menu = { package = "menu2", path = "../menu2" }
settings = { package = "settings2", path = "../settings2" }
theme = { package = "theme2", path = "../theme2" }
workspace = { package = "workspace2", path = "../workspace2" }

anyhow.workspace = true
smallvec.workspace = true
