[package]
name = "workspace2_ui"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/workspace2_ui.rs"

[dependencies]
ui = { package = "ui2", path = "../ui2", features = ["stories"] }
gpui = { package = "gpui2", path = "../gpui2" }
theme = { path = "../theme2", package = "theme2" }
log = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
assets = { path = "../assets" }
clap = { version = "3.1", features = ["derive"] }
picker = { package = "picker2", path = "../picker2" }
rust-embed = { workspace = true }
settings = { path = "../settings2", package = "settings2" }
simplelog = "0.9"
util = { path = "../util" }
workspace = { path = "../workspace2", package = "workspace2" }
