name = "Rust"
path_suffixes = ["rs"]
indent = 4

idents = [
    { inside = "let_declaration" },
    { inside = "field_declaration" },
    { start = "where_clause", end = ["block", "field_declaration_list"] },
    { after = "{", before = "}" },
    { start = "(", end = ")" },
    { start = "[", end = "]" },
]
