name = "JavaScript"
path_suffixes = ["js", "jsx", "mjs"]
line_comment = "// "
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "`", end = "`", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "/*", end = " */", close = true, newline = false, not_in = ["comment", "string"] },
]

[overrides.element]
line_comment = { remove = true }
block_comment = ["{/* ", " */}"]
