[package]
name = "journal2"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/journal2.rs"
doctest = false

[dependencies]
editor = { path = "../editor" }
gpui = { package = "gpui2", path = "../gpui2" }
util = { path = "../util" }
workspace = { path = "../workspace" }
settings2 = { path = "../settings2" }

anyhow.workspace = true
chrono = "0.4"
dirs = "4.0"
serde.workspace = true
schemars.workspace = true
log.workspace = true
shellexpand = "2.1.0"

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
