[package]
name = "assets"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/assets.rs"

[dependencies]
anyhow.workspace = true
gpui = { path = "../gpui2", package = "gpui2" }
parking_lot.workspace = true
rust-embed.workspace = true
