[workspace]
members = [
    "crates/activity_indicator",
    "crates/assets",
    "crates/auto_update",
    "crates/breadcrumbs",
    "crates/call",
    "crates/cli",
    "crates/client",
    "crates/clock",
    "crates/collab",
    "crates/collab_ui",
    "crates/collections",
    "crates/command_palette",
    "crates/context_menu",
    "crates/db",
    "crates/diagnostics",
    "crates/drag_and_drop",
    "crates/editor",
    "crates/file_finder",
    "crates/fs",
    "crates/fsevent",
    "crates/fuzzy",
    "crates/git",
    "crates/go_to_line",
    "crates/gpui",
    "crates/gpui_macros",
    "crates/journal",
    "crates/language",
    "crates/live_kit_client",
    "crates/live_kit_server",
    "crates/lsp",
    "crates/media",
    "crates/menu",
    "crates/outline",
    "crates/picker",
    "crates/plugin",
    "crates/plugin_macros",
    "crates/plugin_runtime",
    "crates/project",
    "crates/project_panel",
    "crates/project_symbols",
    "crates/rope",
    "crates/rpc",
    "crates/search",
    "crates/settings",
    "crates/snippet",
    "crates/sum_tree",
    "crates/terminal",
    "crates/text",
    "crates/theme",
    "crates/theme_selector",
    "crates/theme_testbench",
    "crates/util",
    "crates/vim",
    "crates/workspace",
    "crates/zed",
]
default-members = ["crates/zed"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["preserve_order", "raw_value"] }
rand = { version = "0.8" }

[patch.crates-io]
tree-sitter = { git = "https://github.com/tree-sitter/tree-sitter", rev = "36b5b6c89e55ad1a502f8b3234bb3e12ec83a5da" }
async-task = { git = "https://github.com/zed-industries/async-task", rev = "341b57d6de98cdfd7b418567b8de2022ca993a6e" }
sqlx = { git = "https://github.com/launchbadge/sqlx", rev = "4b7053807c705df312bcb9b6281e184bf7534eb3" }

# TODO - Remove when a version is released with this PR: https://github.com/servo/core-foundation-rs/pull/457
cocoa = { git = "https://github.com/servo/core-foundation-rs", rev = "079665882507dd5e2ff77db3de5070c1f6c0fb85" }
cocoa-foundation = { git = "https://github.com/servo/core-foundation-rs", rev = "079665882507dd5e2ff77db3de5070c1f6c0fb85" }
core-foundation = { git = "https://github.com/servo/core-foundation-rs", rev = "079665882507dd5e2ff77db3de5070c1f6c0fb85" }
core-foundation-sys = { git = "https://github.com/servo/core-foundation-rs", rev = "079665882507dd5e2ff77db3de5070c1f6c0fb85" }
core-graphics = { git = "https://github.com/servo/core-foundation-rs", rev = "079665882507dd5e2ff77db3de5070c1f6c0fb85" }

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
debug = true

