[package]
name = "pando"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/pando.rs"

[features]
test-support = []

[dependencies]
anyhow = "1.0.38"
client = { path = "../client" }
gpui = { path = "../gpui" }
settings = { path = "../settings" }
theme = { path = "../theme" }
workspace = { path = "../workspace" }
sqlez = { path = "../sqlez" }
sqlez_macros = { path = "../sqlez_macros" }