[package]
name = "quick_action_bar"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/quick_action_bar.rs"
doctest = false

[dependencies]
assistant = { path = "../assistant" }
editor = { path = "../editor" }
gpui = { package = "gpui2", path = "../gpui2" }
search = { path = "../search" }
workspace = { path = "../workspace" }
ui = { package = "ui2", path = "../ui2" }

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
gpui = { package = "gpui2", path = "../gpui2", features = ["test-support"] }
workspace = { path = "../workspace", features = ["test-support"] }
