[package]
name = "notebook"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/notebook.rs"
doctest = false

[dependencies]
collections = { path = "../collections" }

schemafy = "0.6"
schemafy_core = "0.6"
serde = "1.0"
serde_json = "1.0"
