[package]
name = "menu"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/menu.rs"
doctest = false

[dependencies]
gpui = { package = "gpui2", path = "../gpui2" }
serde = { workspace = true }
