[package]
name = "buffer"
version = "0.1.0"
edition = "2018"

[features]
test-support = ["rand"]

[dependencies]
anyhow = "1.0.38"
arrayvec = "0.7.1"
clock = { path = "../clock" }
gpui = { path = "../gpui" }
lazy_static = "1.4"
log = "0.4"
parking_lot = "0.11.1"
rand = { version = "0.8.3", optional = true }
seahash = "4.1"
serde = { version = "1", features = ["derive"] }
similar = "1.3"
smallvec = { version = "1.6", features = ["union"] }
sum_tree = { path = "../sum_tree" }
tree-sitter = "0.19.5"
zrpc = { path = "../zrpc" }

[dev-dependencies]
rand = "0.8.3"
tree-sitter-rust = "0.19.0"
unindent = "0.1.7"
