[package]
name = "playground_ui"
version = "0.1.0"
edition = "2021"

[lib]
name = "playground_ui"
path = "src/playground_ui.rs"
crate-type = ["dylib"]

[dependencies]
collections = { path = "../../../collections" }
util = { path = "../../../util" }
gpui = { path = "../.." }
derive_more = "0.99.17"
log.workspace = true
optional_struct = "0.3.1"
smallvec.workspace = true
serde.workspace = true

[dev-dependencies]
gpui = { path = "../..", features = ["test-support"] }
