[package]
name = "ai"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/ai.rs"
doctest = false

[dependencies]
collections = { path = "../collections"}
editor = { path = "../editor" }
fs = { path = "../fs" }
gpui = { path = "../gpui" }
language = { path = "../language" }
menu = { path = "../menu" }
search = { path = "../search" }
settings = { path = "../settings" }
theme = { path = "../theme" }
util = { path = "../util" }
workspace = { path = "../workspace" }

anyhow.workspace = true
chrono = "0.4"
futures.workspace = true
isahc.workspace = true
regex.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
smol.workspace = true
tiktoken-rs = "0.4"

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
