[package]
name = "worktree"
version = "0.1.0"
edition = "2018"

[features]
test-support = []

[dependencies]
anyhow = "1.0.38"
async-trait = "0.1"
buffer = { path = "../buffer" }
clock = { path = "../clock" }
fsevent = { path = "../fsevent" }
futures = "0.3"
fuzzy = { path = "../fuzzy" }
gpui = { path = "../gpui" }
ignore = "0.4"
lazy_static = "1.4.0"
libc = "0.2"
log = "0.4"
parking_lot = "0.11.1"
postage = { version = "0.4.1", features = ["futures-traits"] }
rpc_client = { path = "../rpc_client" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0.64", features = ["preserve_order"] }
smol = "1.2.5"
sum_tree = { path = "../sum_tree" }
util = { path = "../util" }
toml = "0.5"
rpc = { path = "../rpc" }

[dev-dependencies]
rand = "0.8.3"
rpc_client = { path = "../rpc_client", features = ["test-support"] }
tempdir = { version = "0.3.7" }
util = { path = "../util", features = ["test-support"] }
rpc = { path = "../rpc", features = ["test-support"] }
