[package]
name = "fuzzy"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/fuzzy.rs"
doctest = false

[dependencies]
gpui = { package = "gpui2", path = "../gpui2" }
util = { path = "../util" }
