[package]
name = "theme_selector"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/theme_selector.rs"
doctest = false

[dependencies]
editor = { path = "../editor" }
fuzzy = { path = "../fuzzy" }
gpui = { path = "../gpui" }
picker = { path = "../picker" }
theme = { path = "../theme" }
settings = { path = "../settings" }
workspace = { path = "../workspace" }
util = { path = "../util" }
log = { version = "0.4.16", features = ["kv_unstable_serde"] }
parking_lot = "0.11.1"
postage = { workspace = true }
smol = "1.2.5"
