[package]
name = "theme_selector"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/theme_selector.rs"
doctest = false

[dependencies]
editor = { path = "../editor" }
fuzzy = { path = "../fuzzy" }
fs = { path = "../fs" }
gpui = { path = "../gpui" }
picker = { path = "../picker" }
theme = { path = "../theme" }
settings = { path = "../settings" }
feature_flags = { path = "../feature_flags" }
workspace = { path = "../workspace" }
util = { path = "../util" }
log.workspace = true
parking_lot.workspace = true
postage.workspace = true
smol.workspace = true

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
