[package]
name = "theme_selector"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/theme_selector.rs"
doctest = false

[dependencies]
client = { package = "client2", path = "../client2" }
editor = { path = "../editor" }
feature_flags = { path = "../feature_flags" }
fs = { package = "fs2", path = "../fs2" }
fuzzy = { package = "fuzzy2", path = "../fuzzy2" }
gpui = { package = "gpui2", path = "../gpui2" }
picker = { path = "../picker" }
settings = { package = "settings2", path = "../settings2" }
theme = { package = "theme2", path = "../theme2" }
ui = { package = "ui2", path = "../ui2" }
util = { path = "../util" }
workspace = { path = "../workspace" }
log.workspace = true
parking_lot.workspace = true
postage.workspace = true
smol.workspace = true

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
