[package]
name = "workspace_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpui = {path = "../gpui"}
text = {path = "../text"}
lsp = {path = "../lsp"}
rpc = {path = "../rpc"}
language = {path = "../language"}
project_types = {path = "../project_types"}
serde.workspace = true
