[package]
name = "storybook3"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "storybook"
path = "src/storybook3.rs"

[dependencies]
anyhow.workspace = true

gpui = { package = "gpui2", path = "../gpui2" }
ui = { package = "ui2", path = "../ui2", features = ["stories"] }
theme = { package = "theme2", path = "../theme2", features = ["stories"] }
settings = { package = "settings2", path = "../settings2"}
