[package]
name = "util"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/util.rs"
doctest = true

[features]
test-support = ["tempdir", "git2"]

[dependencies]
anyhow = "1.0.38"
backtrace = "0.3"
log = { version = "0.4.16", features = ["kv_unstable_serde"] }
lazy_static = "1.4.0"
futures = { workspace = true }
isahc = "1.7"
smol = "1.2.5"
url = "2.2"
rand = { workspace = true }
tempdir = { version = "0.3.7", optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
git2 = { version = "0.15", default-features = false, optional = true }
dirs = "3.0"

[dev-dependencies]
tempdir = { version = "0.3.7" }
git2 = { version = "0.15", default-features = false }
