[package]
name = "util"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/util.rs"
doctest = true

[features]
test-support = []

[dependencies]
anyhow.workspace = true
backtrace = "0.3"
log.workspace = true
lazy_static.workspace = true
futures.workspace = true
smol.workspace = true

rand.workspace = true
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true
dirs = "3.0"
take-until = "0.2.0"

[dev-dependencies]
tempdir.workspace = true
git2 = { version = "0.15", default-features = false }
