[package]
name = "util"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[features]
test-support = ["rand", "serde_json", "tempdir"]

[dependencies]
anyhow = "1.0.38"
futures = "0.3"
log = { version = "0.4.16", features = ["kv_unstable_serde"] }
rand = { version = "0.8", optional = true }
tempdir = { version = "0.3.7", optional = true }
serde_json = { version = "1.0.64", features = [
    "preserve_order",
], optional = true }
