[package]
name = "util"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[features]
test-support = ["clock", "rand", "serde_json", "tempdir"]

[dependencies]
clock = { path = "../clock", optional = true }
anyhow = "1.0.38"
futures = "0.3"
log = "0.4"
rand = { version = "0.8", optional = true }
surf = "2.2"
tempdir = { version = "0.3.7", optional = true }
serde_json = { version = "1.0.64", features = [
    "preserve_order",
], optional = true }
