[package]
name = "audio2"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/audio2.rs"
doctest = false

[dependencies]
gpui = { package = "gpui2", path = "../gpui2" }
collections = { path = "../collections" }
util = { path = "../util" }


rodio ={version = "0.17.1", default-features=false, features = ["wav"]}

log.workspace = true
futures.workspace = true
anyhow.workspace = true
parking_lot.workspace = true

[dev-dependencies]
