[package]
name = "people_panel"
version = "0.1.0"
edition = "2018"

[dependencies]
client = { path = "../client" }
gpui = { path = "../gpui" }
theme = { path = "../theme" }
workspace = { path = "../workspace" }
postage = { version = "0.4.1", features = ["futures-traits"] }
