[package]
name = "recent_projects"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/recent_projects.rs"
doctest = false

[dependencies]
editor = { path = "../editor" }
fuzzy = {  path = "../fuzzy" }
gpui = { package = "gpui2", path = "../gpui2" }
language = { path = "../language" }
picker = { path = "../picker" }
settings = { path = "../settings" }
text = { path = "../text" }
util = { path = "../util"}
theme = { package = "theme2", path = "../theme2" }
ui = { path = "../ui" }
workspace = { path = "../workspace" }

futures.workspace = true
ordered-float.workspace = true
postage.workspace = true
smol.workspace = true

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
