[package]
name = "contacts_panel"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/contacts_panel.rs"
doctest = false

[dependencies]
client = { path = "../client" }
editor = { path = "../editor" }
gpui = { path = "../gpui" }
settings = { path = "../settings" }
theme = { path = "../theme" }
util = { path = "../util" }
workspace = { path = "../workspace" }
postage = { version = "0.4.1", features = ["futures-traits"] }
