[package]
authors = ["Nathan Sobo <nathan@warp.dev>"]
default-run = "collab"
edition = "2021"
name = "collab"
version = "0.1.0"

[[bin]]
name = "collab"

[[bin]]
name = "seed"
required-features = ["seed-support"]

[dependencies]
collections = { path = "../collections" }
rpc = { path = "../rpc" }
util = { path = "../util" }

anyhow = "1.0.40"
async-trait = "0.1.50"
async-tungstenite = "0.16"
base64 = "0.13"
envy = "0.4.2"
env_logger = "0.8"
futures = "0.3"
hyper = { version = "0.14", features = ["full"] }
json_env_logger = "0.1"
lipsum = { version = "0.8", optional = true }
log = { version = "0.4.16", features = ["kv_unstable_serde"] }
parking_lot = "0.11.1"
rand = "0.8"
routerify = "3.0"
scrypt = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha-1 = "0.9"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.17"
time = "0.2"
toml = "0.5.8"

[dependencies.sqlx]
version = "0.5.2"
features = ["runtime-async-std-rustls", "postgres", "time", "uuid"]

[dev-dependencies]
collections = { path = "../collections", features = ["test-support"] }
gpui = { path = "../gpui", features = ["test-support"] }
rpc = { path = "../rpc", features = ["test-support"] }
client = { path = "../client", features = ["test-support"] }
editor = { path = "../editor", features = ["test-support"] }
language = { path = "../language", features = ["test-support"] }
lsp = { path = "../lsp", features = ["test-support"] }
project = { path = "../project", features = ["test-support"] }
settings = { path = "../settings", features = ["test-support"] }
theme = { path = "../theme" }
workspace = { path = "../workspace", features = ["test-support"] }
ctor = "0.1"
env_logger = "0.8"
util = { path = "../util" }
lazy_static = "1.4"
serde_json = { version = "1.0.64", features = ["preserve_order"] }

[features]
seed-support = ["lipsum"]
