[package]
name = "language_selector"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/language_selector.rs"
doctest = false

[dependencies]
editor = { path = "../editor" }
fuzzy = {  path = "../fuzzy" }
language = { path = "../language" }
gpui = { package = "gpui2", path = "../gpui2" }
picker = { path = "../picker" }
project = { path = "../project" }
theme = { package = "theme2", path = "../theme2" }
ui = { path = "../ui" }
settings = { path = "../settings" }
util = { path = "../util" }
workspace = { path = "../workspace" }
anyhow.workspace = true

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
