[package]
name = "gpui3"
version = "0.1.0"
edition = "2021"

[features]
test = []

[lib]
path = "src/gpui3.rs"

[dependencies]
anyhow.workspace = true
bytemuck = "1.14.0"
derive_more.workspace = true
font-kit = { git = "https://github.com/zed-industries/font-kit", rev = "b2f77d56f450338aa4f7dd2f0197d8c9acb0cf18" }
itertools = "0.11.0"
log.workspace = true
parking_lot.workspace = true
plane-split = "0.18.0"
raw-window-handle = "0.5.2"
refineable = { path = "../refineable" }
rust-embed.workspace = true
schemars = "0.8"
serde.workspace = true
simplelog = "0.9"
slotmap = "1.0.6"
smallvec.workspace = true
taffy = { git = "https://github.com/DioxusLabs/taffy", rev = "4fb530bdd71609bb1d3f76c6a8bde1ba82805d5e" }
util = { path = "../util" }
wgpu = "0.17.0"
