[package]
name = "project_core"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
client.workspace = true
clock.workspace = true
collections.workspace = true
fs.workspace = true
futures.workspace = true
fuzzy.workspace = true
git.workspace = true
gpui.workspace = true
ignore = "0.4.22"
itertools = "0.12.1"
language.workspace = true
log.workspace = true
lsp.workspace = true
parking_lot.workspace = true
postage.workspace = true
rpc.workspace = true
serde.workspace = true
serde_json.workspace = true
settings.workspace = true
schemars.workspace = true
smol.workspace = true
sum_tree.workspace = true
text.workspace = true
util.workspace = true
