[package]
name = "storybook"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "storybook"
path = "src/storybook.rs"

[dependencies]
anyhow.workspace = true
derive_more.workspace = true
gpui2 = { path = "../gpui2" }
itertools = "0.11.0"
log.workspace = true
refineable = { path = "../refineable" }
rust-embed.workspace = true
serde.workspace = true
settings = { path = "../settings" }
simplelog = "0.9"
slotmap = "1.0.6"
theme = { path = "../theme" }
util = { path = "../util" }

[dev-dependencies]
gpui2 = { path = "../gpui2", features = ["test-support"] }
