name = "Racket"
path_suffixes = ["rkt"]
line_comment = "; "
autoclose_before = "])"
brackets = [
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "'", end = "'", close = false, newline = false },
]
