[package]
name = "project_symbols"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/project_symbols.rs"
doctest = false

[dependencies]
editor = { path = "../editor" }
fuzzy = { package = "fuzzy2",  path = "../fuzzy2" }
gpui = { package = "gpui2",  path = "../gpui2" }
picker = { path = "../picker" }
project = { path = "../project" }
text = { package = "text2",  path = "../text2" }
settings = { package = "settings2",  path = "../settings2" }
workspace = { path = "../workspace" }
theme = { package = "theme2", path = "../theme2" }
util = { path = "../util" }

anyhow.workspace = true
ordered-float.workspace = true
postage.workspace = true
smol.workspace = true

[dev-dependencies]
futures.workspace = true
editor = { path = "../editor", features = ["test-support"] }
settings = { package = "settings2", path = "../settings2", features = ["test-support"] }
gpui = { package = "gpui2", path = "../gpui2", features = ["test-support"] }
language = { package = "language2", path = "../language2", features = ["test-support"] }
lsp = { package = "lsp2", path = "../lsp2", features = ["test-support"] }
project = { path = "../project", features = ["test-support"] }
theme = { package = "theme2", path = "../theme2", features = ["test-support"] }
workspace = { path = "../workspace", features = ["test-support"] }
