[package]
name = "project_symbols"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/project_symbols.rs"
doctest = false

[dependencies]
editor = { path = "../editor" }
fuzzy = {   path = "../fuzzy" }
gpui = { package = "gpui2",  path = "../gpui2" }
picker = { path = "../picker" }
project = { path = "../project" }
text = { package = "text2",  path = "../text2" }
settings = { path = "../settings" }
workspace = { path = "../workspace" }
theme = { package = "theme2", path = "../theme2" }
util = { path = "../util" }

anyhow.workspace = true
ordered-float.workspace = true
postage.workspace = true
smol.workspace = true

[dev-dependencies]
futures.workspace = true
editor = { path = "../editor", features = ["test-support"] }
settings = { path = "../settings", features = ["test-support"] }
gpui = { package = "gpui2", path = "../gpui2", features = ["test-support"] }
language = { path = "../language", features = ["test-support"] }
lsp = { path = "../lsp", features = ["test-support"] }
project = { path = "../project", features = ["test-support"] }
theme = { package = "theme2", path = "../theme2", features = ["test-support"] }
workspace = { path = "../workspace", features = ["test-support"] }
