[package]
name = "outline"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/outline.rs"
doctest = false

[dependencies]
editor = { path = "../editor" }
fuzzy = { path = "../fuzzy" }
gpui = { path = "../gpui" }
language = { path = "../language" }
picker = { path = "../picker" }
settings = { path = "../settings" }
text = { path = "../text" }
workspace = { path = "../workspace" }
ordered-float = "2.1.1"
postage = { workspace = true }
smol = "1.2"
