[package]
name = "outline"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/outline.rs"
doctest = false

[dependencies]
editor = { path = "../editor" }
fuzzy = {  path = "../fuzzy" }
gpui = { package = "gpui2", path = "../gpui2" }
ui = { package = "ui2", path = "../ui2" }
language = { path = "../language" }
picker = { path = "../picker" }
settings = { package = "settings2", path = "../settings2" }
text = { package = "text2", path = "../text2" }
theme = { package = "theme2", path = "../theme2" }
workspace = { path = "../workspace" }
util = { path = "../util" }

ordered-float.workspace = true
postage.workspace = true
smol.workspace = true

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
