[package]
authors = ["Nathan Sobo <nathan@warp.dev>"]
default-run = "zed-server"
edition = "2018"
name = "zed-server"
version = "0.1.0"

[dependencies]
anyhow = "1.0.40"
async-std = { version = "1.8.0", features = ["attributes"] }
async-trait = "0.1.50"
async-tungstenite = "0.14"
base64 = "0.13"
clap = "=3.0.0-beta.2"
comrak = "0.10"
either = "1.6"
envy = "0.4.2"
futures = "0.3"
handlebars = "3.5"
http-auth-basic = "0.1.3"
jwt-simple = "0.10.0"
oauth2 = { version = "4.0.0", default_features = false }
oauth2-surf = "0.1.1"
parking_lot = "0.11.1"
postage = { version = "0.4.1", features = ["futures-traits"] }
rand = "0.8"
rust-embed = "5.9.0"
scrypt = "0.7"
serde = { version = "1.0", features = ["derive"] }
sha-1 = "0.9"
surf = "2.2.0"
tide = "0.16.0"
tide-compress = "0.9.0"
toml = "0.5.8"
zed-rpc = { path = "../zed-rpc" }

[dependencies.async-sqlx-session]
version = "0.3.0"
features = ["pg", "rustls"]
default-features = false

[dependencies.sqlx]
version = "0.5.2"
features = ["runtime-async-std-rustls", "postgres"]

[dev-dependencies]
gpui = { path = "../gpui" }
zed = { path = "../zed", features = ["test-support"] }
lazy_static = "1.4"
serde_json = { version = "1.0.64", features = ["preserve_order"] }
