[package]
name = "journal"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/journal.rs"

[dependencies]
gpui = { path = "../gpui" }
util = { path = "../util" }
workspace = { path = "../workspace" }
anyhow = "1.0"
chrono = "0.4"
dirs = "4.0"
log = "0.4"