[package]
name = "theme"
version = "0.1.0"
edition = "2021"
publish = false

[features]
test-support = ["gpui/test-support"]

[lib]
path = "src/theme.rs"
doctest = false

[dependencies]
gpui = { path = "../gpui" }
fs = { path = "../fs" }
anyhow.workspace = true
indexmap = "1.6.2"
parking_lot.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
toml.workspace = true
