[package]
name = "room"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/room.rs"
doctest = false

[features]
test-support = [
    "client/test-support",
    "collections/test-support",
    "gpui/test-support",
    "project/test-support",
]

[dependencies]
anyhow = "1.0.38"
client = { path = "../client" }
collections = { path = "../collections" }
gpui = { path = "../gpui" }
project = { path = "../project" }

[dev-dependencies]
client = { path = "../client", features = ["test-support"] }
collections = { path = "../collections", features = ["test-support"] }
gpui = { path = "../gpui", features = ["test-support"] }
project = { path = "../project", features = ["test-support"] }
