[package]
name = "capture"
version = "0.1.0"
edition = "2021"
description = "An example of screen capture"

[package.metadata.bundle]
name = "Capture"
identifier = "dev.zed.Capture"

[dependencies]
gpui = { path = "../gpui" }
media = { path = "../media" }

anyhow = "1.0.38"
block = "0.1"
bytes = "1.2"
cocoa = "0.24"
core-foundation = "0.9.3"
core-graphics = "0.22.3"
foreign-types = "0.3"
futures = "0.3"
log = { version = "0.4.16", features = ["kv_unstable_serde"] }
objc = "0.2"
parking_lot = "0.11.1"
postage = { version = "0.4.1", features = ["futures-traits"] }
simplelog = "0.9"

[build-dependencies]
bindgen = "0.59.2"
