extends = "_base"

[surface]
0 = "#222222"
1 = "#0f0b0c"
2 = "#131415"

[border]
0 = "#000000B2"
1 = "#FFFFFF20"

[text]
0 = { extends = "$text.base", color = "#ffffff" }
1 = { extends = "$text.base", color = "#b3b3b3" }
2 = { extends = "$text.base", color = "#7b7d80" }
3 = { extends = "$text.base", color = "#66686A" }

[shadow]
0 = "#00000052"

[selection]
host = { selection = "#3B57BC55", cursor = "$text.0.color" }
guests = [
  { selection = "#FDF35133", cursor = "#FDF351" },
  { selection = "#4EACAD33", cursor = "#4EACAD" },
  { selection = "#D0453B33", cursor = "#D0453B" },
  { selection = "#3B874B33", cursor = "#3B874B" },
  { selection = "#BD7CB433", cursor = "#BD7CB4" },
  { selection = "#EE823133", cursor = "#EE8231" },
  { selection = "#5A2B9233", cursor = "#5A2B92" },
]

[status]
good = "#4fac63"
info = "#3c5dd4"
warn = "#faca50"
bad = "#b7372e"

[state]
active_line = "#161313"
highlighted_line = "#faca5033"
deleted_line = "#dd000036"
inserted_line = "#00dd0036"
hover = "#00000033"
selected = "#00000088"

[editor.syntax]
keyword = { color = "#0086c0", weight = "bold" }
function = "#dcdcaa"
string = "#cb8f77"
type = "#4ec9b0"
number = "#b5cea8"
comment = "#6a9955"
property = "#4e94ce"
variant = "#4fc1ff"
constant = "#9cdcfe"
title = { color = "#9cdcfe", weight = "bold" }
emphasis = "#4ec9b0"
"emphasis.strong" = { color = "#4ec9b0", weight = "bold" }
link_uri = { color = "#6a9955", underline = true }
link_text = { color = "#cb8f77", italic = true }
list_marker = "#4e94ce"
