extends = "_base"

[surface]
0 = "#222324"
1 = "#141516"
2 = "#131415"

[border]
0 = "#0F1011"

[text]
0 = { extends = "$text.base", color = "#ffffff" }
1 = { extends = "$text.base", color = "#b3b3b3" }
2 = { extends = "$text.base", color = "#7b7d80" }
3 = { extends = "$text.base", color = "#66686A" }

[shadow]
0 = "#00000052"

[selection]
host = { selection = "#3B57BC33", cursor = "$text.0.color" }
guests = [
  { selection = "#FDF35133", cursor = "#FDF351" },
  { selection = "#4EACAD33", cursor = "#4EACAD" },
  { selection = "#D0453B33", cursor = "#D0453B" },
  { selection = "#3B874B33", cursor = "#3B874B" },
  { selection = "#BD7CB433", cursor = "#BD7CB4" },
  { selection = "#EE823133", cursor = "#EE8231" },
  { selection = "#5A2B9233", cursor = "#5A2B92" },
]

[status]
good = "#4fac63"
info = "#3c5dd4"
warn = "#faca50"
bad = "#b7372e"

[state]
active_line = "#00000033"
hover = "#00000033"

[editor.syntax]
keyword = { color = "#0086c0", weight = "bold" }
function = "#dcdcaa"
string = "#cb8f77"
type = "#4ec9b0"
number = "#b5cea8"
comment = "#6a9955"
property = "#4e94ce"
variant = "#4fc1ff"
constant = "#9cdcfe"
