[package]
name = "playground"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "playground"
path = "src/playground.rs"

[dependencies]
anyhow.workspace = true
derive_more.workspace = true
gpui = { path = ".." }
log.workspace = true
gpui2_macros = { path = "../../gpui2_macros" }
parking_lot.workspace = true
refineable.workspace = true
rust-embed.workspace = true
serde.workspace = true
settings = { path = "../../settings" }
simplelog = "0.9"
smallvec.workspace = true
theme = { path = "../../theme" }
util = { path = "../../util" }

[dev-dependencies]
gpui = { path = "..", features = ["test-support"] }
