[[bin]]
name = "playground"
path = "src/playground.rs"

[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more.workspace = true
gpui = { path = ".." }
log.workspace = true
optional_struct = "0.3.1"
serde.workspace = true
simplelog = "0.9"
smallvec.workspace = true

[dev-dependencies]
gpui = { path = "..", features = ["test-support"] }
