[[bin]]
name = "playground"
path = "src/playground.rs"

[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
playground_ui = { path = "ui" }

gpui = { path = ".." }
log.workspace = true
simplelog = "0.9"

[dev-dependencies]
gpui = { path = "..", features = ["test-support"] }
