[package]
name = "vim"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/vim.rs"
doctest = false

[features]
neovim = ["nvim-rs", "async-compat", "async-trait", "tokio"]

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_derive.workspace = true
itertools = "0.10"
log.workspace = true

async-compat = { version = "0.2.1", "optional" = true }
async-trait = { workspace = true, "optional" = true }
nvim-rs = { git = "https://github.com/KillTheMule/nvim-rs", branch = "master", features = ["use_tokio"], optional = true }
tokio = { version = "1.15", "optional" = true }
serde_json.workspace = true

collections = { path = "../collections" }
command_palette = { path = "../command_palette" }
editor = { path = "../editor" }
gpui = { package = "gpui2", path = "../gpui2" }
language = { path = "../language" }
search = { path = "../search" }
settings = { package = "settings2", path = "../settings2" }
workspace = { path = "../workspace" }
theme = { package = "theme2", path = "../theme2" }
ui = { package = "ui2", path = "../ui2"}
diagnostics = { path = "../diagnostics" }
zed_actions = { path = "../zed_actions" }

[dev-dependencies]
indoc.workspace = true
parking_lot.workspace = true
futures.workspace = true

editor = { path = "../editor", features = ["test-support"] }
gpui = { package = "gpui2", path = "../gpui2", features = ["test-support"] }
language = { path = "../language", features = ["test-support"] }
project = { path = "../project", features = ["test-support"] }
util = { path = "../util", features = ["test-support"] }
settings = { package = "settings2", path = "../settings2" }
workspace = { path = "../workspace", features = ["test-support"] }
theme = { package = "theme2", path = "../theme2", features = ["test-support"] }
lsp = { path = "../lsp", features = ["test-support"] }
