[text]
base = { family = "Inconsolata", size = 15 }

[workspace]
background = "$surface.0"
pane_divider = { width = 1, color = "$border.0" }

[workspace.titlebar]
border = { width = 1, bottom = true, color = "$border.0" }
title = "$text.0"
avatar_width = 20
icon_color = "$text.2.color"
avatar = { corner_radius = 10, border = { width = 1, color = "#00000088" } }

[workspace.titlebar.offline_icon]
padding = { right = 4 }
width = 16

[workspace.tab]
text = "$text.2"
padding = { left = 12, right = 12 }
icon_width = 8
spacing = 10
icon_close = "$text.2.color"
icon_close_active = "$text.0.color"
icon_dirty = "$status.info"
icon_conflict = "$status.warn"
border = { left = true, bottom = true, width = 1, color = "$border.0" }

[workspace.active_tab]
extends = "$workspace.tab"
background = "$surface.1"
text = "$text.0"

[workspace.sidebar]
width = 32
border = { right = true, width = 1, color = "$border.0" }

[workspace.sidebar.resize_handle]
padding = { left = 1 }
background = "$border.0"

[workspace.sidebar.icon]
color = "$text.2.color"
height = 18

[workspace.sidebar.active_icon]
extends = "$workspace.sidebar.icon"
color = "$text.0.color"

[workspace.left_sidebar]
extends = "$workspace.sidebar"
border = { width = 1, color = "$border.0", right = true }

[workspace.right_sidebar]
extends = "$workspace.sidebar"
border = { width = 1, color = "$border.0", left = true }

[panel]
padding = 12

[chat_panel]
extends = "$panel"
channel_name = { extends = "$text.0", weight = "bold" }
channel_name_hash = { text = "$text.2", padding.right = 8 }

[chat_panel.message]
body = "$text.1"
sender = { extends = "$text.0", weight = "bold", margin.right = 8 }
timestamp = "$text.2"
padding.bottom = 6

[chat_panel.pending_message]
extends = "$chat_panel.message"
body = { color = "$text.3.color" }
sender = { color = "$text.3.color" }
timestamp = { color = "$text.3.color" }

[chat_panel.channel_select.item]
padding = 4
name = "$text.1"
hash = { extends = "$text.2", margin.right = 8 }

[chat_panel.channel_select.hovered_item]
extends = "$chat_panel.channel_select.item"
background = "$state.hover"
corner_radius = 6

[chat_panel.channel_select.active_item]
extends = "$chat_panel.channel_select.item"
name = "$text.0"

[chat_panel.channel_select.hovered_active_item]
extends = "$chat_panel.channel_select.hovered_item"
name = "$text.0"

[chat_panel.channel_select.header]
extends = "$chat_panel.channel_select.active_item"
padding.bottom = 4
padding.left = 0

[chat_panel.channel_select.menu]
padding = 4
corner_radius = 6
border = { color = "$border.0", width = 1 }
background = "$surface.0"
shadow = { offset = [0, 2], blur = 16, color = "$shadow.0" }

[chat_panel.input_editor]
background = "$surface.1"
corner_radius = 6
padding = { left = 8, right = 8, top = 7, bottom = 7 }
text = "$text.0"
placeholder_text = "$text.2"
selection = "$selection.host"
border = { width = 1, color = "$border.0" }

[chat_panel.sign_in_prompt]
extends = "$text.0"
underline = true

[chat_panel.hovered_sign_in_prompt]
extends = "$chat_panel.sign_in_prompt"
color = "$text.1.color"

[people_panel]
extends = "$panel"
host_username = { extends = "$text.0", padding.left = 5 }
worktree_host_avatar = { corner_radius = 10 }
worktree_guest_avatar = { corner_radius = 8 }

[people_panel.worktree_name]
extends = "$text.0"
padding = { left = 5 }

[people_panel.tree_branch]
width = 1
color = "$surface.2"

[selector]
background = "$surface.0"
padding = 8
margin.top = 52
corner_radius = 6
shadow = { offset = [0, 2], blur = 16, color = "$shadow.0" }
border = { width = 1, color = "$border.0" }

[selector.input_editor]
background = "$surface.1"
corner_radius = 6
padding = { left = 16, right = 16, top = 7, bottom = 7 }
text = "$text.0"
placeholder_text = "$text.2"
selection = "$selection.host"
border = { width = 1, color = "$border.0" }

[selector.empty]
text = "$text.2"
padding = { left = 16, right = 16, top = 8, bottom = 4 }

[selector.item]
text = "$text.1"
highlight_text = { extends = "$text.base", color = "$syntax.keyword.color", weight = "$syntax.keyword.weight" }
padding = { left = 16, right = 16, top = 4, bottom = 4 }
corner_radius = 6

[selector.active_item]
extends = "$selector.item"
background = "$state.hover"
text = "$text.0"

[editor]
text = "$text.1"
background = "$surface.1"
gutter_background = "$surface.1"
active_line_background = "$state.active_line"
line_number = "$text.2.color"
line_number_active = "$text.0.color"
selection = "$selection.host"
guest_selections = "$selection.guests"
