[workspace]
background = "$surface.0"

[workspace.tab]
text = "$text.2"
padding = { left = 10, right = 10 }
icon_close = "$text.0"
icon_dirty = "$status.info"
icon_conflict = "$status.warn"

[workspace.active_tab]
extends = "$workspace.tab"
background = "$surface.1"
text = "$text.0"

[workspace.sidebar]
padding = { left = 10, right = 10 }

[workspace.sidebar_icon]
color = "$text.2"

[workspace.active_sidebar_icon]
color = "$text.0"

[selector]
background = "$surface.2"
text = "$text.0"
padding = { top = 6.0, bottom = 6.0, left = 6.0, right = 6.0 }
margin.top = 12.0
corner_radius = 6.0
shadow = { offset = [0.0, 0.0], blur = 12.0, color = "#00000088" }

[selector.item]
background = "#424344"
text = "#cccccc"
highlight_text = { color = "#18a3ff", weight = "bold" }
border = { color = "#000000", width = 1.0 }
padding = { top = 6.0, bottom = 6.0, left = 6.0, right = 6.0 }

[selector.active_item]
extends = "$selector.item"
background = "#094771"

[editor]
background = "$surface.1"
gutter_background = "$surface.1"
active_line_background = "$surface.2"
line_number = "$text.2"
line_number_active = "$text.0"
text = "$text.1"
replicas = [
    { selection = "#264f78", cursor = "$text.0" },
    { selection = "#504f31", cursor = "#fcf154" },
]
