[workspace]
background = "$surface.0"

[workspace.tab]
text = "$text.2"
padding = { left = 10, right = 10 }
icon_close = "$text.0.color"
icon_dirty = "$status.info"
icon_conflict = "$status.warn"

[workspace.active_tab]
extends = "$workspace.tab"
background = "$surface.1"
text = "$text.0"

[workspace.sidebar]
padding = { left = 10, right = 10 }

[workspace.sidebar_icon]
color = "$text.2.color"

[workspace.active_sidebar_icon]
color = "$text.0.color"

[chat_panel]
padding = { top = 10.0, bottom = 10.0, left = 10.0, right = 10.0 }
channel_name = { extends = "$text.0", weight = "bold" }
channel_name_hash = { text = "$text.2", padding.right = 5.0 }

[chat_panel.message]
body = "$text.1"
sender.margin.right = 10.0
sender.text = { extends = "$text.0", weight = "bold" }
timestamp.text = "$text.2"

[selector]
background = "$surface.2"
text = "$text.0"
padding = { top = 6.0, bottom = 6.0, left = 6.0, right = 6.0 }
margin.top = 12.0
corner_radius = 6.0
shadow = { offset = [0.0, 0.0], blur = 12.0, color = "#00000088" }

[selector.item]
background = "#424344"
text = "$text.1"
highlight_text = { extends = "$text.base", color = "#18a3ff", weight = "bold" }
border = { color = "#000000", width = 1.0 }
padding = { top = 6.0, bottom = 6.0, left = 6.0, right = 6.0 }

[selector.active_item]
extends = "$selector.item"
background = "#094771"

[editor]
background = "$surface.1"
gutter_background = "$surface.1"
active_line_background = "$surface.2"
line_number = "$text.2.color"
line_number_active = "$text.0.color"
replicas = [
    { selection = "#264f78", cursor = "$text.0.color" },
    { selection = "#504f31", cursor = "#fcf154" },
]

[syntax]
default = "$text.1.color"
