[workspace]
background = "$surface.0"

[workspace.tab]
text = "$text.2"
padding = { left = 10, right = 10 }
icon_close = "$text.0.color"
icon_dirty = "$status.info"
icon_conflict = "$status.warn"

[workspace.active_tab]
extends = "$workspace.tab"
background = "$surface.1"
text = "$text.0"

[workspace.sidebar.icons]
padding = { left = 10, right = 10 }

[workspace.sidebar.resize_handle]
margin = { left = 6 }

[workspace.sidebar_icon]
color = "$text.2.color"

[workspace.active_sidebar_icon]
color = "$text.0.color"

[chat_panel]
channel_name = { extends = "$text.0", weight = "bold" }
channel_name_hash = { text = "$text.2", padding.right = 5 }

[chat_panel.message]
body = "$text.1"
sender = { extends = "$text.0", weight = "bold", margin.right = 10.0 }
timestamp = "$text.2"
padding = { top = 10, bottom = 10, left = 10, right = 10 }

[chat_panel.channel_select.item]
padding = { top = 4, bottom = 4, left = 4, right = 4 }
name = "$text.1"
hash = { extends = "$text.2", margin.right = 5.0 }

[chat_panel.channel_select.hovered_item]
extends = "$chat_panel.channel_select.item"
background = "$surface.2"
corner_radius = 6.0

[chat_panel.channel_select.active_item]
extends = "$chat_panel.channel_select.item"
name = "$text.0"

[chat_panel.channel_select.hovered_active_item]
extends = "$chat_panel.channel_select.hovered_item"
name = "$text.0"

[chat_panel.channel_select.header]
extends = "$chat_panel.channel_select.active_item"
padding.bottom = 0

[chat_panel.channel_select.menu]
padding = { top = 4, bottom = 4, left = 4, right = 4 }
corner_radius = 6.0
border = { color = "#000000", width = 1.0 }
background = "$surface.0"

[selector]
background = "$surface.2"
text = "$text.0"
padding = { top = 6.0, bottom = 6.0, left = 6.0, right = 6.0 }
margin.top = 12.0
corner_radius = 6.0
shadow = { offset = [0.0, 0.0], blur = 12.0, color = "#00000088" }

[selector.item]
background = "#424344"
text = "$text.1"
highlight_text = { extends = "$text.base", color = "#18a3ff", weight = "bold" }
border = { color = "#000000", width = 1.0 }
padding = { top = 6.0, bottom = 6.0, left = 6.0, right = 6.0 }

[selector.active_item]
extends = "$selector.item"
background = "#094771"

[editor]
background = "$surface.1"
gutter_background = "$surface.1"
active_line_background = "$surface.2"
line_number = "$text.2.color"
line_number_active = "$text.0.color"
replicas = [
    { selection = "#264f78", cursor = "$text.0.color" },
    { selection = "#504f31", cursor = "#fcf154" },
]

[syntax]
default = "$text.1.color"
