extends = "_base"

[surface]
0 = "#050101"
1 = "#131415"
2 = "#1c1d1e"
3 = "#3a3b3c"

[text_color]
dull = "#5a5a5b"
bright = "#ffffff"
normal = "#d4d4d4"

[syntax]
keyword = { color = "#0086c0", weight = "bold" }
function = "#dcdcaa"
string = "#cb8f77"
type = "#4ec9b0"
number = "#b5cea8"
comment = "#6a9955"
property = "#4e94ce"
variant = "#4fc1ff"
constant = "#9cdcfe"
