extends = "_base"

[variables]
elevation_1 = "#050101"
elevation_2 = "#131415"
elevation_3 = "#1c1d1e"
elevation_4 = "#3a3b3c"
text_dull = "#5a5a5b"
text_bright = "#ffffff"
text_normal = "#d4d4d4"

[syntax]
keyword = { color = "#0086c0", weight = "bold" }
function = "#dcdcaa"
string = "#cb8f77"
type = "#4ec9b0"
number = "#b5cea8"
comment = "#6a9955"
property = "#4e94ce"
variant = "#4fc1ff"
constant = "#9cdcfe"
