extends = "_base"

[surface]
0 = "#222324"
1 = "#141516"
2 = "#131415"

[text]
0 = "#ffffff"
1 = "#b3b3b3"
2 = "#7b7d80"

[status]
good = "#4fac63"
info = "#3c5dd4"
warn = "#faca50"
bad = "#b7372e"

[syntax]
keyword = { color = "#0086c0", weight = "bold" }
function = "#dcdcaa"
string = "#cb8f77"
type = "#4ec9b0"
number = "#b5cea8"
comment = "#6a9955"
property = "#4e94ce"
variant = "#4fc1ff"
constant = "#9cdcfe"
