extends = "base"

[variables]
elevation_1 = 0x050101
elevation_2 = 0x131415
elevation_3 = 0x1c1d1e
elevation_4 = 0x3a3b3c
text_dull = 0x5a5a5b
text_bright = 0xffffff
text_normal = 0xd4d4d4

[syntax]
keyword = 0xc586c0
function = 0xdcdcaa
string = 0xcb8f77
type = 0x4ec9b0
number = 0xb5cea8
comment = 0x6a9955
property = 0x4e94ce
variant = 0x4fc1ff
constant = 0x9cdcfe
