extends = "_base"

[surface]
0 = "#ffffff"
1 = "#f3f3f3"
2 = "#ececec"
3 = "#3a3b3c"

[text]
0 = "#acacac"
1 = "#111111"
2 = "#333333"

[status]
good = "#4fac63"
info = "#3c5dd4"
warn = "#faca50"
bad = "#b7372e"

[syntax]
keyword = "#0000fa"
function = "#795e26"
string = "#a82121"
type = "#267f29"
number = "#b5cea8"
comment = "#6a9955"
property = "#4e94ce"
variant = "#4fc1ff"
constant = "#9cdcfe"
