extends = "_base"

[variables]
elevation_1 = "#ffffff"
elevation_2 = "#f3f3f3"
elevation_3 = "#ececec"
elevation_4 = "#3a3b3c"
text_dull = "#acacac"
text_bright = "#111111"
text_normal = "#333333"

[syntax]
keyword = "#0000fa"
function = "#795e26"
string = "#a82121"
type = "#267f29"
number = "#b5cea8"
comment = "#6a9955"
property = "#4e94ce"
variant = "#4fc1ff"
constant = "#9cdcfe"
