[package]
name = "rpc_client"
version = "0.1.0"
edition = "2018"

[features]
test-support = []

[dependencies]
anyhow = "1.0.38"
async-recursion = "0.3"
async-tungstenite = { version = "0.14", features = ["async-tls"] }
gpui = { path = "../gpui" }
lazy_static = "1.4.0"
log = "0.4"
parking_lot = "0.11.1"
postage = { version = "0.4.1", features = ["futures-traits"] }
rand = "0.8.3"
smol = "1.2.5"
surf = "2.2"
thiserror = "1.0.29"
tiny_http = "0.8"
util = { path = "../util" }
rpc = { path = "../rpc" }
