[package]
name = "breadcrumbs"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/breadcrumbs.rs"
doctest = false

[dependencies]
collections = { path = "../collections" }
editor = { path = "../editor" }
gpui = { package = "gpui2", path = "../gpui2" }
ui = { path = "../ui" }
language = { path = "../language" }
project = { path = "../project" }
search = { path = "../search" }
settings = { path = "../settings" }
theme = { package = "theme2", path = "../theme2" }
workspace = { path = "../workspace" }
outline = { path = "../outline" }
itertools = "0.10"

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
gpui = { package = "gpui2", path = "../gpui2", features = ["test-support"] }
workspace = { path = "../workspace", features = ["test-support"] }
