[package]
name = "find"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/find.rs"

[dependencies]
collections = { path = "../collections" }
editor = { path = "../editor" }
gpui = { path = "../gpui" }
theme = { path = "../theme" }
workspace = { path = "../workspace" }
aho-corasick = "0.7"
anyhow = "1.0"
postage = { version = "0.4.1", features = ["futures-traits"] }
regex = "1.5"
smol = { version = "1.2" }
