[package]
name = "find"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/find.rs"

[dependencies]
collections = { path = "../collections" }
editor = { path = "../editor" }
gpui = { path = "../gpui" }
language = { path = "../language" }
project = { path = "../project" }
theme = { path = "../theme" }
workspace = { path = "../workspace" }
anyhow = "1.0"
postage = { version = "0.4.1", features = ["futures-traits"] }

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
gpui = { path = "../gpui", features = ["test-support"] }
workspace = { path = "../workspace", features = ["test-support"] }
unindent = "0.1"
