apiVersion: batch/v1
kind: Job
metadata:
  namespace: ${ZED_KUBE_NAMESPACE}
  name: ${ZED_MIGRATE_JOB_NAME}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrator
          image: ${ZED_IMAGE_ID}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database
                  key: url
