[package]
name = "live_kit_server"
version = "0.1.0"
edition = "2021"
description = "SDK for the LiveKit server API"

[lib]
path = "src/live_kit_server.rs"
doctest = false

[dependencies]
anyhow = "1.0.38"
hmac = "0.12"
jwt = "0.16"
hyper = { version = "0.14", features = ["client", "http1"] }
prost = "0.8"
prost-types = "0.8"
serde = { version = "1.0", features = ["derive", "rc"] }
sha2 = "0.10"

[build-dependencies]
prost-build = "0.9"
