[package]
name = "copilot_button"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/copilot_button.rs"
doctest = false

[dependencies]
copilot = { package = "copilot2", path = "../copilot2" }
editor = { path = "../editor" }
fs = { package = "fs2", path = "../fs2" }
zed-actions = { package="zed_actions2", path = "../zed_actions2"}
gpui = { package = "gpui2", path = "../gpui2" }
language = { package = "language2", path = "../language2" }
settings = { package = "settings2", path = "../settings2" }
theme = { package = "theme2", path = "../theme2" }
util = { path = "../util" }
workspace = { package = "workspace2", path = "../workspace2" }
anyhow.workspace = true
smol.workspace = true
futures.workspace = true

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
