[package]
name = "copilot_button"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/copilot_button.rs"
doctest = false

[dependencies]
assets = { path = "../assets" }
copilot = { path = "../copilot" }
editor = { path = "../editor" }
fs = { path = "../fs" }
context_menu = { path = "../context_menu" }
gpui = { path = "../gpui" }
language = { path = "../language" }
settings = { path = "../settings" }
theme = { path = "../theme" }
util = { path = "../util" }
workspace = { path = "../workspace" }
anyhow.workspace = true
smol.workspace = true
futures.workspace = true

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
