[package]
name = "copilot_button"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/copilot_button.rs"
doctest = false

[dependencies]
copilot = { path = "../copilot" }
editor = { path = "../editor" }
fs = { package = "fs2", path = "../fs2" }
zed_actions = { path = "../zed_actions"}
gpui = { package = "gpui2", path = "../gpui2" }
language = { path = "../language" }
settings = { package = "settings2", path = "../settings2" }
theme = { package = "theme2", path = "../theme2" }
util = { path = "../util" }
workspace = {path = "../workspace" }
anyhow.workspace = true
smol.workspace = true
futures.workspace = true

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
