[package]
name = "zed_uppercase"
version = "0.0.5"
edition = "2021"
publish = false
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/uppercase.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = {path= "../../crates/extension_api"}
serde_json = "1.0"
