[package]
name = "feedback"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/feedback.rs"

[features]
test-support = []

[dependencies]
anyhow = "1.0.38"
client = { path = "../client" }
editor = { path = "../editor" }
futures = "0.3"
gpui = { path = "../gpui" }
human_bytes = "0.4.1"
isahc = "1.7"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive", "rc"] }
settings = { path = "../settings" }
sysinfo = "0.27.1"
urlencoding = "2.1.2"
util = { path = "../util" }
workspace = { path = "../workspace" }