[package]
name = "ureq_client"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[lints]
workspace = true

[features]
test-support = []

[lib]
path = "src/ureq_client.rs"
doctest = true

[[example]]
name = "ureq_example"
path = "examples/ureq_example.rs"

[dependencies]
anyhow.workspace = true
futures.workspace = true
gpui.workspace = true
http_client.workspace = true
parking_lot.workspace = true
serde.workspace = true
smol.workspace = true
ureq = "3.0.0-rc1"
util.workspace = true


[dev-dependencies]
gpui = {workspace = true, features = ["test-support"]}
