[package]
name = "storybook2"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "storybook"
path = "src/storybook2.rs"

[dependencies]
anyhow.workspace = true
gpui3 = { path = "../gpui3" }
log.workspace = true
rust-embed.workspace = true
serde.workspace = true
settings = { path = "../settings" }
simplelog = "0.9"
theme = { path = "../theme" }
util = { path = "../util" }

[dev-dependencies]
gpui3 = { path = "../gpui3", features = ["test"] }
