[package]
name = "prettier"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/prettier.rs"

[dependencies]
language = { path = "../language" }
gpui = { path = "../gpui" }
fs = { path = "../fs" }
node_runtime = { path = "../node_runtime"}
util = { path = "../util" }

serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
anyhow.workspace = true
futures.workspace = true

[dev-dependencies]
language = { path = "../language", features = ["test-support"] }
gpui = { path = "../gpui", features = ["test-support"] }
fs = { path = "../fs",  features = ["test-support"] }
