[package]
name = "db"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/db.rs"
doctest = false

[features]
test-support = []

[dependencies]
indoc = "1.0.4"
collections = { path = "../collections" }
gpui = { path = "../gpui" }
anyhow = "1.0.57"
async-trait = "0.1"
lazy_static = "1.4.0"
log = { version = "0.4.16", features = ["kv_unstable_serde"] }
parking_lot = "0.11.1"
sqlez = { git = "https://github.com/Kethku/sqlez", ref = "c8c01fe6b82085bbfe81b2a9406718454a7839c4c" }

[dev-dependencies]
gpui = { path = "../gpui", features = ["test-support"] }
tempdir = { version = "0.3.7" }
env_logger = "0.9.1"