[package]
name = "workspace2"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/workspace2.rs"
doctest = false

[features]
test-support = [
    "call2/test-support",
    "client2/test-support",
    "project2/test-support",
    "settings2/test-support",
    "gpui/test-support",
    "fs2/test-support"
]

[dependencies]
db2 = { path = "../db2" }
client2 = { path = "../client2" }
collections = { path = "../collections" }
# context_menu = { path = "../context_menu" }
fs2 = { path = "../fs2" }
gpui = { package = "gpui2", path = "../gpui2" }
install_cli2 = { path = "../install_cli2" }
language2 = { path = "../language2" }
#menu = { path = "../menu" }
node_runtime = { path = "../node_runtime" }
project2 = { path = "../project2" }
settings2 = { path = "../settings2" }
terminal2 = { path = "../terminal2" }
theme2 = { path = "../theme2" }
util = { path = "../util" }
ui = { package = "ui2", path = "../ui2" }

async-recursion = "1.0.0"
itertools = "0.10"
bincode = "1.2.1"
anyhow.workspace = true
futures.workspace = true
lazy_static.workspace = true
log.workspace = true
parking_lot.workspace = true
postage.workspace = true
schemars.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
smallvec.workspace = true
uuid.workspace = true

[dev-dependencies]
call2 = { path = "../call2", features = ["test-support"] }
client2 = { path = "../client2", features = ["test-support"] }
gpui = { package = "gpui2", path = "../gpui2", features = ["test-support"] }
project2 = { path = "../project2", features = ["test-support"] }
settings2 = { path = "../settings2", features = ["test-support"] }
fs2 = { path = "../fs2", features = ["test-support"] }
db2 = { path = "../db2", features = ["test-support"] }

indoc.workspace = true
env_logger.workspace = true
