[package]
name = "settings"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/settings.rs"
doctest = false

[features]
test-support = ["theme/test-support", "gpui/test-support", "fs/test-support"]

[dependencies]
assets = { path = "../assets" }
collections = { path = "../collections" }
gpui = { path = "../gpui" }
sqlez = { path = "../sqlez" }
fs = { path = "../fs" }
anyhow.workspace = true
futures.workspace = true
theme = { path = "../theme" }
staff_mode = { path = "../staff_mode" }
util = { path = "../util" }

glob.workspace = true
json_comments = "0.2"
lazy_static.workspace = true
postage.workspace = true
schemars.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
smallvec.workspace = true
toml = "0.5"
tree-sitter = "*"
tree-sitter-json = "*"

[dev-dependencies]
gpui = { path = "../gpui", features = ["test-support"] }
fs = { path = "../fs", features = ["test-support"] }
theme = { path = "../theme", features = ["test-support"] }

pretty_assertions = "1.3.0"
unindent.workspace = true
