[package]
name = "miner"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[[bin]]
name = "miner"
path = "src/miner.rs"

[dependencies]
anyhow.workspace = true
futures.workspace = true
project.workspace = true
reqwest = { version = "0.12.5", features = ["json", "stream"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
