[package]
name = "miner"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[[bin]]
name = "miner"
path = "src/miner.rs"

[features]
test-support = [
    "collections/test-support",
    "fs/test-support",
    "gpui/test-support",
]

[dependencies]
anyhow.workspace = true
async-watch.workspace = true
collections.workspace = true
clap.workspace = true
futures.workspace = true
fs.workspace = true
git.workspace = true
gpui.workspace = true
heed.workspace = true
ignore.workspace = true
indicatif = "0.17.8"
reqwest = { version = "0.12.5", features = ["json", "stream"] }
serde.workspace = true
serde_json.workspace = true
tree-sitter.workspace = true
tree-sitter-rust.workspace = true
tokenizers = { version = "0.19.1", features = ["http"] }

[dev-dependencies]
collections = { workspace = true, features = ["test-support"] }
fs = { workspace = true, features = ["test-support"] }
gpui = { workspace = true, features = ["test-support"] }
