[package]
name = "crdb"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/crdb.rs"
doctest = false

[dependencies]
rope = { path = "../rope" }
sum_tree = { path = "../sum_tree" }
collections = { path = "../collections" }

anyhow.workspace = true
futures.workspace = true
lazy_static.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
smallvec.workspace = true
uuid = { version = "1.3", features = ["v4", "fast-rng", "serde"] }

[dev-dependencies]
gpui = { path = "../gpui", features = ["test-support"] }
async-broadcast = "0.4"
rand.workspace = true
