[package]
name = "crdb"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/copilot.rs"
doctest = false

[dependencies]
rope = { path = "../rope" }
sum_tree = { path = "../sum_tree" }

parking_lot.workspace = true
smallvec.workspace = true
uuid = { version = "1.3", features = ["v4", "fast-rng"] }
