[package]
name = "welcome"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/welcome.rs"

[features]
test-support = []

[dependencies]
client = { path = "../client" }
editor = { path = "../editor" }
fs = { path = "../fs" }
fuzzy = {  path = "../fuzzy" }
gpui = { package = "gpui2", path = "../gpui2" }
ui = { path = "../ui" }
db = { path = "../db" }
install_cli = { path = "../install_cli" }
project = { path = "../project" }
settings = { path = "../settings" }
theme = { package = "theme2", path = "../theme2" }
theme_selector = { path = "../theme_selector" }
util = { path = "../util" }
picker = { path = "../picker" }
workspace = { path = "../workspace" }
vim = { path = "../vim" }

anyhow.workspace = true
log.workspace = true
schemars.workspace = true
serde.workspace = true

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
