[package]
name = "welcome"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/welcome.rs"

[features]
test-support = []

[dependencies]
client = { package = "client2", path = "../client2" }
editor = { path = "../editor" }
fs = { package = "fs2", path = "../fs2" }
fuzzy = {  path = "../fuzzy" }
gpui = { package = "gpui2", path = "../gpui2" }
ui = { package = "ui2", path = "../ui2" }
db = { package = "db2", path = "../db2" }
install_cli = { path = "../install_cli" }
project = { path = "../project" }
settings = { package = "settings2", path = "../settings2" }
theme = { package = "theme2", path = "../theme2" }
theme_selector = { path = "../theme_selector" }
util = { path = "../util" }
picker = { path = "../picker" }
workspace = { path = "../workspace" }
vim = { path = "../vim" }

anyhow.workspace = true
log.workspace = true
schemars.workspace = true
serde.workspace = true

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
