[book]
authors = ["The Zed Team"]
language = "en"
multilingual = false
src = "src"
title = "Zed"
site-url = "/docs2/"

[output.html]
no-section-label = true
preferred-dark-theme = "light"

[output.html.print]
enable = false

[output.html.redirect]
"/elixir.html" = "/languages/elixir.html"
"/javascript.html" = "/languages/javascript.html"
"/ruby.html" = "/languages/ruby.html"
"/python.html" = "/languages/python.html"
