[package]
name = "rope"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/rope.rs"

[dependencies]
bromberg_sl2 = { git = "https://github.com/zed-industries/bromberg_sl2", rev = "dac565a90e8f9245f48ff46225c915dc50f76920" }
smallvec = { version = "1.6", features = ["union"] }
sum_tree = { path = "../sum_tree" }
arrayvec = "0.7.1"
log = { version = "0.4.16", features = ["kv_unstable_serde"] }
util = { path = "../util" }

[dev-dependencies]
rand = "0.8.3"
util = { path = "../util", features = ["test-support"] }
gpui = { path = "../gpui", features = ["test-support"]  }
