[package]
name = "lsp_status"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lsp_status.rs"
doctest = false

[dependencies]
editor = { path = "../editor" }
language = { path = "../language" }
gpui = { path = "../gpui" }
project = { path = "../project" }
settings = { path = "../settings" }
util = { path = "../util" }
workspace = { path = "../workspace" }
futures = "0.3"
smallvec = { version = "1.6", features = ["union"] }
