[package]
name = "picker"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/picker.rs"
doctest = false

[dependencies]
editor = { path = "../editor" }
ui = { package = "ui2", path = "../ui2" }
gpui = { package = "gpui2", path = "../gpui2" }
menu = { package = "menu2", path = "../menu2" }
settings = { package = "settings2", path = "../settings2" }
util = { path = "../util" }
theme = { package = "theme2", path = "../theme2" }
workspace = { path = "../workspace"}

parking_lot.workspace = true

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
gpui = { package = "gpui2", path = "../gpui2", features = ["test-support"] }
serde_json.workspace = true
ctor.workspace = true
env_logger.workspace = true
