[package]
name = "picker"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/picker.rs"
doctest = false

[dependencies]
editor = { path = "../editor" }
fuzzy = { path = "../fuzzy" }
gpui = { path = "../gpui" }
menu = { path = "../menu" }
parking_lot.workspace = true
settings = { path = "../settings" }
theme = { path = "../theme" }
ui = { path = "../ui" }
util = { path = "../util" }
workspace = { path = "../workspace"}

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
gpui = { path = "../gpui", features = ["test-support"] }
serde_json.workspace = true
ctor.workspace = true
env_logger.workspace = true
