[package]
name = "scripting"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lib]
path = "src/scripting.rs"
doctest = false

[dependencies]
v8 = "0.83"
gpui.workspace = true
# rust_jsc = "0.1.0"
