name = "Rust"
path_suffixes = ["rs"]
autoclose_pairs = [
    { start = "{", end = "}" },
    { start = "[", end = "]" },
    { start = "(", end = ")" },
    { start = "\"", end = "\"" },
    { start = "/*", end = " */" },
]
