name: Publish Collab Server Image

on:
  push:
    tags:
      - collab-v*

env:
  DOCKER_BUILDKIT: 1
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

jobs:
  publish:
    name: Publish collab server image 
    runs-on:
      - self-hosted
      - deploy
    steps:
      - name: Add Rust to the PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sign into DigitalOcean docker registry
        run: doctl registry login

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          clean: false
          submodules: 'recursive'

      - name: Check that tag version matches package version
        run: |
          set -eu
          crate_version=$(script/get-crate-version collab)
          tag_version=$(echo $GITHUB_REF_NAME | sed -e 's/collab-v//')
          if [[ $tag_version != $crate_version ]]; then
            echo "collab crate version $crate_version does not match git tag version $tag_version"
            exit 1
          fi
          echo "Publishing collab version: $crate_version"
          echo "COLLAB_VERSION=$crate_version" >> $GITHUB_ENV

      - name: Build docker image
        run: docker build . --tag registry.digitalocean.com/zed/collab:v${COLLAB_VERSION}
    
      - name: Publish docker image
        run: docker push registry.digitalocean.com/zed/collab:v${COLLAB_VERSION}
