name: Randomized Tests

concurrency: randomized-tests

on:
  push:
    branches:
      - main
      - randomized-tests-runner
  schedule:
     - cron: '*/15 * * * *'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  tests:
    name: Run randomized tests
    runs-on:
      - self-hosted
      - randomized-tests
    steps:
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup update stable

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          clean: false
          submodules: 'recursive'

      - name: Run randomized tests
        run: script/randomized-test-ci
