on:
  release:
    types: [published]

jobs:
  discord_release:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      if: ${{ ! github.event.release.prerelease }}
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        content: |
          📣 Zed ${{ github.event.release.tag_name }} was just released!
          
          Restart your Zed or head to https://zed.dev/releases to grab it.
        
          ```md
          ### Changelog
          
          ${{ github.event.release.body }}
